In [210]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score,f1_score,recall_score,precision_score,classification_report,confusion_matrix



In [166]:
df=pd.read_csv("dirty_v3_path.csv")

In [167]:
df.head()

Age  Gender Medical Condition  Glucose  Blood Pressure    BMI  \
0  46.0    Male          Diabetes   137.04          135.27  28.90   
1  22.0    Male           Healthy    71.58          113.27  26.29   
2  50.0     NaN            Asthma    95.24             NaN  22.53   
3  57.0     NaN           Obesity      NaN          130.53  38.47   
4  66.0  Female      Hypertension    95.15          178.17  31.12   

   Oxygen Saturation  LengthOfStay  Cholesterol  Triglycerides  HbA1c  \
0              96.04             6       231.88         210.56   7.61   
1              97.54             2       165.57         129.41   4.91   
2              90.31             2       214.94         165.35   5.60   
3              96.60             5       197.71         182.13   6.92   
4              94.90             4       259.53         115.85   5.98   

   Smoking  Alcohol  Physical Activity  Diet Score  Family History  \
0        0        0              -0.20        3.54               0   
1        0        0               8.12        5.90               0   
2        0        0               5.01        4.65               1   
3        0        0               3.16        3.37               0   
4        0        1               3.56        3.40               0   

   Stress Level  Sleep Hours random_notes   noise_col  
0          5.07         6.05        lorem -137.057211  
1          5.87         7.72        ipsum  -11.230610  
2          3.09         4.82        ipsum   98.331195  
3          3.01         5.33        lorem   44.187175  
4          6.38         6.64        lorem   44.831426

In [168]:
df['Medical Condition']

0            Diabetes
1             Healthy
2              Asthma
3             Obesity
4        Hypertension
             ...     
29995         Healthy
29996          Asthma
29997             NaN
29998        Diabetes
29999    Hypertension
Name: Medical Condition, Length: 30000, dtype: object

In [169]:



df.describe()
df.isna().sum()


Age                  4500
Gender               4500
Medical Condition    4500
Glucose              4500
Blood Pressure       4500
BMI                     0
Oxygen Saturation       0
LengthOfStay            0
Cholesterol             0
Triglycerides           0
HbA1c                   0
Smoking                 0
Alcohol                 0
Physical Activity       0
Diet Score              0
Family History          0
Stress Level            0
Sleep Hours             0
random_notes            0
noise_col               0
dtype: int64

In [170]:
df.tail()

Age  Gender Medical Condition  Glucose  Blood Pressure    BMI  \
29995  54.0  Female           Healthy    86.35          127.68  28.30   
29996  41.0    Male            Asthma    89.24          154.37  24.93   
29997  83.0  Female               NaN      NaN          170.11  30.55   
29998  41.0    Male          Diabetes   242.87          152.97  23.57   
29999  46.0  Female      Hypertension    86.52          159.26  34.55   

       Oxygen Saturation  LengthOfStay  Cholesterol  Triglycerides  HbA1c  \
29995              94.36             1       218.60         152.82   4.85   
29996              96.07             4       198.30         176.81   5.36   
29997              97.83             3       210.13         168.76   5.05   
29998              99.17             3       208.86         224.21   7.59   
29999              96.60             4       217.37         141.28   5.77   

       Smoking  Alcohol  Physical Activity  Diet Score  Family History  \
29995        0        0               9.15       10.35               0   
29996        1        0               3.34        3.40               0   
29997        0        0               4.53        4.50               0   
29998        0        0               3.16        2.59               0   
29999        1        0               4.91        5.82               1   

       Stress Level  Sleep Hours random_notes   noise_col  
29995          3.65         8.71        ipsum   89.573837  
29996          6.72         2.81        lorem   -5.864517  
29997          4.31         3.61          ###  -30.934595  
29998          7.10         5.80        ipsum    5.085258  
29999          3.64         5.47        lorem -142.559559

In [171]:
df.describe()

Age       Glucose  Blood Pressure           BMI  \
count  25500.000000  25500.000000    25500.000000  30000.000000   
mean      54.616784    123.622179      140.455337     28.476155   
std       15.973618     41.576943       21.077933      5.728804   
min       10.000000     20.320000       74.240000      7.670000   
25%       45.000000     96.280000      125.140000     24.590000   
50%       55.000000    110.500000      138.320000     28.050000   
75%       66.000000    136.610000      153.790000     31.810000   
max       89.000000    318.510000      226.380000     56.850000   

       Oxygen Saturation  LengthOfStay   Cholesterol  Triglycerides  \
count       30000.000000  30000.000000  30000.000000   30000.000000   
mean           94.954992      4.414133    213.033891     176.837375   
std             3.736202      2.761536     33.519757      48.812827   
min            67.510000      1.000000     95.730000     -22.480000   
25%            93.000000      3.000000    189.500000     141.280000   
50%            95.300000      4.000000    211.835000     173.365000   
75%            97.380000      5.000000    235.310000     208.630000   
max           110.070000     19.000000    358.370000     421.510000   

              HbA1c       Smoking       Alcohol  Physical Activity  \
count  30000.000000  30000.000000  30000.000000       30000.000000   
mean       6.294377      0.279767      0.238533           3.803214   
std        1.320269      0.448892      0.426194           2.011729   
min        3.280000      0.000000      0.000000          -3.680000   
25%        5.330000      0.000000      0.000000           2.350000   
50%        5.970000      0.000000      0.000000           3.590000   
75%        6.920000      1.000000      0.000000           5.060000   
max       12.360000      1.000000      1.000000          12.410000   

         Diet Score  Family History  Stress Level   Sleep Hours     noise_col  
count  30000.000000    30000.000000  30000.000000  30000.000000  30000.000000  
mean       4.029654        0.439433      5.917312      6.229836     -0.517010  
std        1.817165        0.496326      2.225057      1.187669    100.076959  
min       -1.750000        0.000000     -2.440000      1.590000   -412.169596  
25%        2.770000        0.000000      4.370000      5.410000    -68.270749  
50%        3.790000        0.000000      5.900000      6.230000     -0.510742  
75%        5.020000        1.000000      7.440000      7.050000     66.811399  
max       12.060000        1.000000     15.450000     10.350000    467.894910

In [172]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 20 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Age                25500 non-null  float64
 1   Gender             25500 non-null  object 
 2   Medical Condition  25500 non-null  object 
 3   Glucose            25500 non-null  float64
 4   Blood Pressure     25500 non-null  float64
 5   BMI                30000 non-null  float64
 6   Oxygen Saturation  30000 non-null  float64
 7   LengthOfStay       30000 non-null  int64  
 8   Cholesterol        30000 non-null  float64
 9   Triglycerides      30000 non-null  float64
 10  HbA1c              30000 non-null  float64
 11  Smoking            30000 non-null  int64  
 12  Alcohol            30000 non-null  int64  
 13  Physical Activity  30000 non-null  float64
 14  Diet Score         30000 non-null  float64
 15  Family History     30000 non-null  int64  
 16  Stress Level       300

In [173]:
df=df.drop(["random_notes","noise_col"],axis = 1)

In [174]:
df.columns

Index(['Age', 'Gender', 'Medical Condition', 'Glucose', 'Blood Pressure',
       'BMI', 'Oxygen Saturation', 'LengthOfStay', 'Cholesterol',
       'Triglycerides', 'HbA1c', 'Smoking', 'Alcohol', 'Physical Activity',
       'Diet Score', 'Family History', 'Stress Level', 'Sleep Hours'],
      dtype='object')

In [175]:

print (df)

        Age  Gender Medical Condition  Glucose  Blood Pressure    BMI  \
0      46.0    Male          Diabetes   137.04          135.27  28.90   
1      22.0    Male           Healthy    71.58          113.27  26.29   
2      50.0     NaN            Asthma    95.24             NaN  22.53   
3      57.0     NaN           Obesity      NaN          130.53  38.47   
4      66.0  Female      Hypertension    95.15          178.17  31.12   
...     ...     ...               ...      ...             ...    ...   
29995  54.0  Female           Healthy    86.35          127.68  28.30   
29996  41.0    Male            Asthma    89.24          154.37  24.93   
29997  83.0  Female               NaN      NaN          170.11  30.55   
29998  41.0    Male          Diabetes   242.87          152.97  23.57   
29999  46.0  Female      Hypertension    86.52          159.26  34.55   

       Oxygen Saturation  LengthOfStay  Cholesterol  Triglycerides  HbA1c  \
0                  96.04             6       2

In [176]:
df.describe()

Age       Glucose  Blood Pressure           BMI  \
count  25500.000000  25500.000000    25500.000000  30000.000000   
mean      54.616784    123.622179      140.455337     28.476155   
std       15.973618     41.576943       21.077933      5.728804   
min       10.000000     20.320000       74.240000      7.670000   
25%       45.000000     96.280000      125.140000     24.590000   
50%       55.000000    110.500000      138.320000     28.050000   
75%       66.000000    136.610000      153.790000     31.810000   
max       89.000000    318.510000      226.380000     56.850000   

       Oxygen Saturation  LengthOfStay   Cholesterol  Triglycerides  \
count       30000.000000  30000.000000  30000.000000   30000.000000   
mean           94.954992      4.414133    213.033891     176.837375   
std             3.736202      2.761536     33.519757      48.812827   
min            67.510000      1.000000     95.730000     -22.480000   
25%            93.000000      3.000000    189.500000     141.280000   
50%            95.300000      4.000000    211.835000     173.365000   
75%            97.380000      5.000000    235.310000     208.630000   
max           110.070000     19.000000    358.370000     421.510000   

              HbA1c       Smoking       Alcohol  Physical Activity  \
count  30000.000000  30000.000000  30000.000000       30000.000000   
mean       6.294377      0.279767      0.238533           3.803214   
std        1.320269      0.448892      0.426194           2.011729   
min        3.280000      0.000000      0.000000          -3.680000   
25%        5.330000      0.000000      0.000000           2.350000   
50%        5.970000      0.000000      0.000000           3.590000   
75%        6.920000      1.000000      0.000000           5.060000   
max       12.360000      1.000000      1.000000          12.410000   

         Diet Score  Family History  Stress Level   Sleep Hours  
count  30000.000000    30000.000000  30000.000000  30000.000000  
mean       4.029654        0.439433      5.917312      6.229836  
std        1.817165        0.496326      2.225057      1.187669  
min       -1.750000        0.000000     -2.440000      1.590000  
25%        2.770000        0.000000      4.370000      5.410000  
50%        3.790000        0.000000      5.900000      6.230000  
75%        5.020000        1.000000      7.440000      7.050000  
max       12.060000        1.000000     15.450000     10.350000

In [177]:
le =LabelEncoder()
df["Gender"]=le.fit_transform(df["Gender"])

In [178]:
df.tail()

Age  Gender Medical Condition  Glucose  Blood Pressure    BMI  \
29995  54.0       0           Healthy    86.35          127.68  28.30   
29996  41.0       1            Asthma    89.24          154.37  24.93   
29997  83.0       0               NaN      NaN          170.11  30.55   
29998  41.0       1          Diabetes   242.87          152.97  23.57   
29999  46.0       0      Hypertension    86.52          159.26  34.55   

       Oxygen Saturation  LengthOfStay  Cholesterol  Triglycerides  HbA1c  \
29995              94.36             1       218.60         152.82   4.85   
29996              96.07             4       198.30         176.81   5.36   
29997              97.83             3       210.13         168.76   5.05   
29998              99.17             3       208.86         224.21   7.59   
29999              96.60             4       217.37         141.28   5.77   

       Smoking  Alcohol  Physical Activity  Diet Score  Family History  \
29995        0        0               9.15       10.35               0   
29996        1        0               3.34        3.40               0   
29997        0        0               4.53        4.50               0   
29998        0        0               3.16        2.59               0   
29999        1        0               4.91        5.82               1   

       Stress Level  Sleep Hours  
29995          3.65         8.71  
29996          6.72         2.81  
29997          4.31         3.61  
29998          7.10         5.80  
29999          3.64         5.47

In [179]:
le =LabelEncoder()
df["Medical Condition"]=le.fit_transform(df["Medical Condition"])

In [180]:
df.tail()

Age  Gender  Medical Condition  Glucose  Blood Pressure    BMI  \
29995  54.0       0                  4    86.35          127.68  28.30   
29996  41.0       1                  1    89.24          154.37  24.93   
29997  83.0       0                  7      NaN          170.11  30.55   
29998  41.0       1                  3   242.87          152.97  23.57   
29999  46.0       0                  5    86.52          159.26  34.55   

       Oxygen Saturation  LengthOfStay  Cholesterol  Triglycerides  HbA1c  \
29995              94.36             1       218.60         152.82   4.85   
29996              96.07             4       198.30         176.81   5.36   
29997              97.83             3       210.13         168.76   5.05   
29998              99.17             3       208.86         224.21   7.59   
29999              96.60             4       217.37         141.28   5.77   

       Smoking  Alcohol  Physical Activity  Diet Score  Family History  \
29995        0        0               9.15       10.35               0   
29996        1        0               3.34        3.40               0   
29997        0        0               4.53        4.50               0   
29998        0        0               3.16        2.59               0   
29999        1        0               4.91        5.82               1   

       Stress Level  Sleep Hours  
29995          3.65         8.71  
29996          6.72         2.81  
29997          4.31         3.61  
29998          7.10         5.80  
29999          3.64         5.47

In [181]:
df.corr()

Age    Gender  Medical Condition   Glucose  \
Age                1.000000 -0.004542          -0.010166  0.117522   
Gender            -0.004542  1.000000           0.009808 -0.007877   
Medical Condition -0.010166  0.009808           1.000000 -0.103043   
Glucose            0.117522 -0.007877          -0.103043  1.000000   
Blood Pressure     0.325402 -0.003697           0.201837  0.055369   
BMI               -0.011306  0.002674           0.240855  0.073653   
Oxygen Saturation  0.077035  0.011181           0.158889 -0.001803   
LengthOfStay       0.110510  0.002238          -0.168535  0.231057   
Cholesterol        0.177479 -0.000944           0.145570  0.005763   
Triglycerides      0.109877 -0.002929           0.144228  0.067150   
HbA1c              0.101566 -0.007110          -0.081686  0.614375   
Smoking            0.061329  0.003278           0.037591 -0.044221   
Alcohol            0.044674 -0.002284           0.072600 -0.022379   
Physical Activity -0.123842 -0.010543          -0.073193 -0.236447   
Diet Score        -0.165724 -0.009920          -0.067908 -0.310729   
Family History     0.115076  0.000271           0.026664  0.152690   
Stress Level       0.170411  0.001283           0.005089  0.070625   
Sleep Hours       -0.082379  0.000928           0.083020 -0.125035   

                   Blood Pressure       BMI  Oxygen Saturation  LengthOfStay  \
Age                      0.325402 -0.011306           0.077035      0.110510   
Gender                  -0.003697  0.002674           0.011181      0.002238   
Medical Condition        0.201837  0.240855           0.158889     -0.168535   
Glucose                  0.055369  0.073653          -0.001803      0.231057   
Blood Pressure           1.000000  0.072683           0.009387      0.037274   
BMI                      0.072683  1.000000           0.066021      0.001351   
Oxygen Saturation        0.009387  0.066021           1.000000     -0.145913   
LengthOfStay             0.037274  0.001351          -0.145913      1.000000   
Cholesterol              0.260067  0.131115          -0.023322      0.100028   
Triglycerides            0.186207  0.186505          -0.009648      0.080654   
HbA1c                    0.047022  0.125447          -0.007675      0.240723   
Smoking                  0.115888 -0.002459          -0.045577      0.094633   
Alcohol                  0.067201  0.040261           0.011794      0.031196   
Physical Activity       -0.137457 -0.346375          -0.016846     -0.183073   
Diet Score              -0.193494 -0.296641           0.025911     -0.241152   
Family History           0.111301  0.057824          -0.000745      0.051304   
Stress Level             0.221543 -0.012055          -0.105826      0.264238   
Sleep Hours             -0.150193 -0.022468           0.167804     -0.253759   

                   Cholesterol  Triglycerides     HbA1c   Smoking   Alcohol  \
Age                   0.177479       0.109877  0.101566  0.061329  0.044674   
Gender               -0.000944      -0.002929 -0.007110  0.003278 -0.002284   
Medical Condition     0.145570       0.144228 -0.081686  0.037591  0.072600   
Glucose               0.005763       0.067150  0.614375 -0.044221 -0.022379   
Blood Pressure        0.260067       0.186207  0.047022  0.115888  0.067201   
BMI                   0.131115       0.186505  0.125447 -0.002459  0.040261   
Oxygen Saturation    -0.023322      -0.009648 -0.007675 -0.045577  0.011794   
LengthOfStay          0.100028       0.080654  0.240723  0.094633  0.031196   
Cholesterol           1.000000       0.178466  0.025627  0.081800  0.064311   
Triglycerides         0.178466       1.000000  0.089357  0.059926  0.047892   
HbA1c                 0.025627       0.089357  1.000000 -0.045991 -0.018405   
Smoking               0.081800       0.059926 -0.045991  1.000000  0.034497   
Alcohol               0.064311       0.047892 -0.018405  0.034497  1.000000   
Physical Activity    -0.208002      -0.258722 -0.284669 -0.022837 

In [182]:
x=df.drop('Medical Condition',axis=1)
y=df['Medical Condition']

In [183]:
model = LogisticRegression()
xtrain, xtest, ytrain, ytest = train_test_split(x, y , test_size=0.2 , random_state=123)

In [184]:
df.isna().sum()

Age                  4500
Gender                  0
Medical Condition       0
Glucose              4500
Blood Pressure       4500
BMI                     0
Oxygen Saturation       0
LengthOfStay            0
Cholesterol             0
Triglycerides           0
HbA1c                   0
Smoking                 0
Alcohol                 0
Physical Activity       0
Diet Score              0
Family History          0
Stress Level            0
Sleep Hours             0
dtype: int64

In [192]:
df.isna().sum()

Gender               0
Medical Condition    0
BMI                  0
Oxygen Saturation    0
LengthOfStay         0
Cholesterol          0
Triglycerides        0
HbA1c                0
Smoking              0
Alcohol              0
Physical Activity    0
Diet Score           0
Family History       0
Stress Level         0
Sleep Hours          0
dtype: int64

In [187]:
print(len(xtrain), len(ytrain))



24000 24000


In [196]:
print(xtrain.isnull().sum())

Age                  3581
Gender                  0
Glucose              3586
Blood Pressure       3630
BMI                     0
Oxygen Saturation       0
LengthOfStay            0
Cholesterol             0
Triglycerides           0
HbA1c                   0
Smoking                 0
Alcohol                 0
Physical Activity       0
Diet Score              0
Family History          0
Stress Level            0
Sleep Hours             0
dtype: int64


In [198]:
xtrain = xtrain.fillna(xtrain.mean())
xtest = xtest.fillna(xtrain.mean()) 

In [199]:
xtrain = xtrain.fillna(xtrain.median())
xtest = xtest.fillna(xtrain.median())

In [200]:
for col in xtrain.select_dtypes(include=['object']).columns:
    xtrain[col] = xtrain[col].fillna(xtrain[col].mode()[0])
    xtest[col] = xtest[col].fillna(xtrain[col].mode()[0])

In [201]:
xtrain = xtrain.dropna()
ytrain = ytrain[xtrain.index] 

In [202]:
model.fit(xtrain, ytrain)

c:\Users\hp\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [203]:
y_pred=model.predict(xtest)

In [204]:
print(y_pred)

[7 7 6 ... 3 5 3]


In [206]:
acc=accuracy_score(ytest,y_pred)
print (acc)

0.6496666666666666


In [213]:
print(confusion_matrix(ytest,y_pred))


[[ 150    5    0    0   14  137   33   66]
 [   2  153    1    2   51  107   20   82]
 [   8   14  142   19    2   37    1   11]
 [  12    2    0 1033    5   95   60   68]
 [   8   11    0    0  561    7    2   21]
 [  58    5    0   25    6 1198   38   74]
 [   2   30    0    5   17   56  604   57]
 [  32   37   38  197  111  274  137   57]]


In [214]:
print(classification_report(ytest,y_pred))

              precision    recall  f1-score   support

           0       0.55      0.37      0.44       405
           1       0.60      0.37      0.45       418
           2       0.78      0.61      0.68       234
           3       0.81      0.81      0.81      1275
           4       0.73      0.92      0.81       610
           5       0.63      0.85      0.72      1404
           6       0.67      0.78      0.73       771
           7       0.13      0.06      0.09       883

    accuracy                           0.65      6000
   macro avg       0.61      0.60      0.59      6000
weighted avg       0.61      0.65      0.62      6000

